In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
df = pd.read_csv(r'C:\Users\user\OneDrive\Desktop\Data Science\Student-Performance-Prediction-System\csv\Student_Performance.csv')

In [18]:
df

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,12047,17,female,public,phd,1.8,55.2,yes,15-30 min,no,mixed,55.8,48.5,46.7,46.1,e
24996,1102,16,female,private,diploma,2.7,97.1,yes,<15 min,no,coaching,64.8,48.2,52.3,56.5,d
24997,4422,19,other,private,post graduate,1.0,63.0,yes,<15 min,no,group study,50.5,20.3,36.1,36.7,f
24998,7858,14,male,private,diploma,1.0,69.4,yes,15-30 min,yes,group study,13.0,34.2,7.3,34.1,f
24999,11621,18,other,public,no formal,0.7,60.3,yes,30-60 min,no,mixed,36.5,45.1,16.5,31.4,f

In [19]:
df.isna().sum()

student_id               0
age                      0
gender                   0
school_type              0
parent_education         0
study_hours              0
attendance_percentage    0
internet_access          0
travel_time              0
extra_activities         0
study_method             0
math_score               0
science_score            0
english_score            0
overall_score            0
final_grade              0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(10000)

In [21]:
df.drop_duplicates()

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,17,male,private,graduate,1.8,53.2,yes,15-30 min,no,group study,37.1,37.1,26.8,38.4,f
14996,14997,17,other,private,diploma,6.7,63.5,no,<15 min,yes,mixed,84.4,67.2,96.2,78.8,c
14997,14998,17,male,private,phd,5.2,58.2,yes,30-60 min,no,group study,69.0,57.2,74.1,64.3,d
14998,14999,16,other,private,graduate,1.0,68.7,yes,30-60 min,yes,textbook,24.2,41.4,30.5,33.6,f
14999,15000,14,other,public,no formal,0.9,54.5,yes,30-60 min,yes,group study,54.0,31.1,35.7,37.7,f

In [22]:
df.drop(['math_score','science_score','english_score','student_id','final_grade'],axis=1,inplace=True)

In [23]:
df

,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,overall_score
0,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,53.1
1,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,61.3
2,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,89.6
3,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,41.6
4,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,25.4
...,...,...,...,...,...,...,...,...,...,...,...
24995,17,female,public,phd,1.8,55.2,yes,15-30 min,no,mixed,46.1
24996,16,female,private,diploma,2.7,97.1,yes,<15 min,no,coaching,56.5
24997,19,other,private,post graduate,1.0,63.0,yes,<15 min,no,group study,36.7
24998,14,male,private,diploma,1.0,69.4,yes,15-30 min,yes,group study,34.1
24999,18,other,public,no formal,0.7,60.3,yes,30-60 min,no,mixed,31.4

In [24]:
df['gender'].unique()

<StringArray>
['male', 'female', 'other']
Length: 3, dtype: str

In [25]:
gender_dict = { 'male':0,'female':1,'other':2}
df['gender'] = df['gender'].map(gender_dict)

In [26]:
df

,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,overall_score
0,14,0,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,53.1
1,18,1,public,graduate,3.7,87.8,yes,>60 min,no,textbook,61.3
2,17,1,private,post graduate,7.9,65.5,no,<15 min,no,notes,89.6
3,16,2,public,high school,1.1,58.1,no,15-30 min,no,notes,41.6
4,16,1,public,high school,1.3,61.0,yes,30-60 min,yes,group study,25.4
...,...,...,...,...,...,...,...,...,...,...,...
24995,17,1,public,phd,1.8,55.2,yes,15-30 min,no,mixed,46.1
24996,16,1,private,diploma,2.7,97.1,yes,<15 min,no,coaching,56.5
24997,19,2,private,post graduate,1.0,63.0,yes,<15 min,no,group study,36.7
24998,14,0,private,diploma,1.0,69.4,yes,15-30 min,yes,group study,34.1
24999,18,2,public,no formal,0.7,60.3,yes,30-60 min,no,mixed,31.4

In [27]:
df['school_type'].unique()

<StringArray>
['public', 'private']
Length: 2, dtype: str

In [28]:
school_dict = {'public':0, 'private':1}
df['school_type'] = df['school_type'].map(school_dict)

In [29]:
df

,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,overall_score
0,14,0,0,post graduate,3.1,84.3,yes,<15 min,yes,notes,53.1
1,18,1,0,graduate,3.7,87.8,yes,>60 min,no,textbook,61.3
2,17,1,1,post graduate,7.9,65.5,no,<15 min,no,notes,89.6
3,16,2,0,high school,1.1,58.1,no,15-30 min,no,notes,41.6
4,16,1,0,high school,1.3,61.0,yes,30-60 min,yes,group study,25.4
...,...,...,...,...,...,...,...,...,...,...,...
24995,17,1,0,phd,1.8,55.2,yes,15-30 min,no,mixed,46.1
24996,16,1,1,diploma,2.7,97.1,yes,<15 min,no,coaching,56.5
24997,19,2,1,post graduate,1.0,63.0,yes,<15 min,no,group study,36.7
24998,14,0,1,diploma,1.0,69.4,yes,15-30 min,yes,group study,34.1
24999,18,2,0,no formal,0.7,60.3,yes,30-60 min,no,mixed,31.4

In [30]:
df['parent_education'].unique()

<StringArray>
['post graduate', 'graduate', 'high school', 'no formal', 'diploma', 'phd']
Length: 6, dtype: str

In [31]:
parent_dict = {'post graduate':0, 'graduate':1, 'high school':2, 'no formal':3, 'diploma':4, 'phd':5}
df['parent_education'] = df['parent_education'].map(parent_dict)

In [32]:
df

,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,overall_score
0,14,0,0,0,3.1,84.3,yes,<15 min,yes,notes,53.1
1,18,1,0,1,3.7,87.8,yes,>60 min,no,textbook,61.3
2,17,1,1,0,7.9,65.5,no,<15 min,no,notes,89.6
3,16,2,0,2,1.1,58.1,no,15-30 min,no,notes,41.6
4,16,1,0,2,1.3,61.0,yes,30-60 min,yes,group study,25.4
...,...,...,...,...,...,...,...,...,...,...,...
24995,17,1,0,5,1.8,55.2,yes,15-30 min,no,mixed,46.1
24996,16,1,1,4,2.7,97.1,yes,<15 min,no,coaching,56.5
24997,19,2,1,0,1.0,63.0,yes,<15 min,no,group study,36.7
24998,14,0,1,4,1.0,69.4,yes,15-30 min,yes,group study,34.1
24999,18,2,0,3,0.7,60.3,yes,30-60 min,no,mixed,31.4

In [33]:
internet_dict = {'yes':0,'no':1}
df['internet_access'] = df['internet_access'].map(internet_dict)

In [34]:
df

,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,overall_score
0,14,0,0,0,3.1,84.3,0,<15 min,yes,notes,53.1
1,18,1,0,1,3.7,87.8,0,>60 min,no,textbook,61.3
2,17,1,1,0,7.9,65.5,1,<15 min,no,notes,89.6
3,16,2,0,2,1.1,58.1,1,15-30 min,no,notes,41.6
4,16,1,0,2,1.3,61.0,0,30-60 min,yes,group study,25.4
...,...,...,...,...,...,...,...,...,...,...,...
24995,17,1,0,5,1.8,55.2,0,15-30 min,no,mixed,46.1
24996,16,1,1,4,2.7,97.1,0,<15 min,no,coaching,56.5
24997,19,2,1,0,1.0,63.0,0,<15 min,no,group study,36.7
24998,14,0,1,4,1.0,69.4,0,15-30 min,yes,group study,34.1
24999,18,2,0,3,0.7,60.3,0,30-60 min,no,mixed,31.4

In [35]:
df['travel_time'].unique()

<StringArray>
['<15 min', '>60 min', '15-30 min', '30-60 min']
Length: 4, dtype: str

In [36]:
travel_dict = {'<15 min':0, '>60 min':1, '15-30 min':2, '30-60 min':3}
df['travel_time'] = df['travel_time'].map(travel_dict)

In [37]:
df

,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,overall_score
0,14,0,0,0,3.1,84.3,0,0,yes,notes,53.1
1,18,1,0,1,3.7,87.8,0,1,no,textbook,61.3
2,17,1,1,0,7.9,65.5,1,0,no,notes,89.6
3,16,2,0,2,1.1,58.1,1,2,no,notes,41.6
4,16,1,0,2,1.3,61.0,0,3,yes,group study,25.4
...,...,...,...,...,...,...,...,...,...,...,...
24995,17,1,0,5,1.8,55.2,0,2,no,mixed,46.1
24996,16,1,1,4,2.7,97.1,0,0,no,coaching,56.5
24997,19,2,1,0,1.0,63.0,0,0,no,group study,36.7
24998,14,0,1,4,1.0,69.4,0,2,yes,group study,34.1
24999,18,2,0,3,0.7,60.3,0,3,no,mixed,31.4

In [38]:
extra_activity_dict = {'yes':0,'no':1}
df['extra_activities'] = df['extra_activities'].map(extra_activity_dict)

In [39]:
df

,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,overall_score
0,14,0,0,0,3.1,84.3,0,0,0,notes,53.1
1,18,1,0,1,3.7,87.8,0,1,1,textbook,61.3
2,17,1,1,0,7.9,65.5,1,0,1,notes,89.6
3,16,2,0,2,1.1,58.1,1,2,1,notes,41.6
4,16,1,0,2,1.3,61.0,0,3,0,group study,25.4
...,...,...,...,...,...,...,...,...,...,...,...
24995,17,1,0,5,1.8,55.2,0,2,1,mixed,46.1
24996,16,1,1,4,2.7,97.1,0,0,1,coaching,56.5
24997,19,2,1,0,1.0,63.0,0,0,1,group study,36.7
24998,14,0,1,4,1.0,69.4,0,2,0,group study,34.1
24999,18,2,0,3,0.7,60.3,0,3,1,mixed,31.4

In [40]:
df['study_method'].unique()

<StringArray>
['notes', 'textbook', 'group study', 'coaching', 'mixed', 'online videos']
Length: 6, dtype: str

In [41]:
study_method_dict = {'notes':0, 'textbook':1, 'group study':2, 'coaching':3, 'mixed':4, 'online videos':5}
df['study_method'] = df['study_method'].map(study_method_dict)

In [42]:
df

,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,overall_score
0,14,0,0,0,3.1,84.3,0,0,0,0,53.1
1,18,1,0,1,3.7,87.8,0,1,1,1,61.3
2,17,1,1,0,7.9,65.5,1,0,1,0,89.6
3,16,2,0,2,1.1,58.1,1,2,1,0,41.6
4,16,1,0,2,1.3,61.0,0,3,0,2,25.4
...,...,...,...,...,...,...,...,...,...,...,...
24995,17,1,0,5,1.8,55.2,0,2,1,4,46.1
24996,16,1,1,4,2.7,97.1,0,0,1,3,56.5
24997,19,2,1,0,1.0,63.0,0,0,1,2,36.7
24998,14,0,1,4,1.0,69.4,0,2,0,2,34.1
24999,18,2,0,3,0.7,60.3,0,3,1,4,31.4

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    25000 non-null  int64
 1   gender                 25000 non-null  int64
 2   school_type            25000 non-null  int64
 3   parent_education       25000 non-null  int64
 4   study_hours            25000 non-null  float64
 5   attendance_percentage  25000 non-null  float64
 6   internet_access        25000 non-null  int64
 7   travel_time            25000 non-null  int64
 8   extra_activities       25000 non-null  int64
 9   study_method           25000 non-null  int64
 10  overall_score          25000 non-null  float64
dtypes: float64(3), int64(8)
memory usage: 2.1 MB

In [44]:
df.to_csv('Cleaned_student.csv')